server {
    listen 80;
    listen [::]:80;
    server_name nikitaabashevst.fvds.ru;

    root /var/www/volnoyebot;
    index index.html;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type text/plain;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
